import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";

export default function WebCallMock() {
  const { mode = "video" } = useLocalSearchParams<{ mode?: "audio" | "video" }>();
  const [muted, setMuted] = useState(false);
  const [cameraOn, setCameraOn] = useState(mode !== "audio");
  const [sharing, setSharing] = useState(false);

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#071A31]" className="flex-1"><View style={styles.page}><View style={styles.top}><View><Text style={styles.encrypted}>KẾT NỐI ĐƯỢC MÃ HÓA P2P</Text><Text style={styles.name}>Cuộc gọi thử nghiệm</Text></View><View style={styles.timer}><View style={styles.onlineDot} /><Text style={styles.timerText}>00:24</Text></View></View><View style={styles.stage}>{sharing ? <View style={styles.shareCanvas}><View style={styles.shareHeader}><Text style={styles.shareTitle}>Đang chia sẻ màn hình</Text><Text style={styles.shareSub}>Người bên kia có thể nhìn thấy nội dung bạn chọn chia sẻ.</Text></View><View style={styles.shareCards}><View style={styles.shareCard} /><View style={styles.shareCard} /><View style={[styles.shareCard, styles.shareCardWide]} /></View></View> : <View style={styles.person}><View style={styles.avatar}><Text style={styles.initials}>KN</Text></View><Text style={styles.personName}>Người bạn Kết Nối</Text><Text style={styles.connection}>{mode === "audio" ? "Đang gọi thoại" : "Đang gọi video"} · P2P ưu tiên</Text></View>}<View style={styles.selfView}><Text style={styles.selfLabel}>{cameraOn ? "Camera của bạn" : "Camera đã tắt"}</Text></View></View><Text style={styles.note}>Bản web là mô phỏng điều khiển. Gọi P2P, camera và chia sẻ màn hình thật chạy trên Development Build.</Text><View style={styles.controls}><Control label={muted ? "Bật mic" : "Tắt mic"} active={muted} onPress={() => setMuted((value) => !value)} /><Control label={cameraOn ? "Tắt camera" : "Bật camera"} active={!cameraOn} onPress={() => setCameraOn((value) => !value)} /><Control label={sharing ? "Dừng chia sẻ" : "Chia sẻ"} active={sharing} onPress={() => setSharing((value) => !value)} /><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.end, pressed && styles.pressed]}><Text style={styles.endText}>Kết thúc</Text></Pressable></View></View></ScreenContainer>;
}

function Control({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.control, active && styles.controlActive, pressed && styles.pressed]}><Text style={[styles.controlText, active && styles.controlTextActive]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ page: { flex: 1, padding: 18 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, encrypted: { color: "#76B8FF", fontSize: 10, letterSpacing: 0.8, fontWeight: "900" }, name: { marginTop: 5, color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, timer: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 12, backgroundColor: "#153653" }, onlineDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#39C985" }, timerText: { color: "#DDEBFA", fontWeight: "800", fontSize: 12 }, stage: { flex: 1, marginTop: 18, overflow: "hidden", borderRadius: 26, backgroundColor: "#0E2A49", borderWidth: 1, borderColor: "#294A6D" }, person: { flex: 1, alignItems: "center", justifyContent: "center" }, avatar: { width: 104, height: 104, borderRadius: 52, backgroundColor: "#267BE0", alignItems: "center", justifyContent: "center", borderWidth: 4, borderColor: "#7DC0FF" }, initials: { color: "#FFFFFF", fontWeight: "900", fontSize: 32 }, personName: { marginTop: 16, color: "#FFFFFF", fontSize: 19, fontWeight: "900" }, connection: { marginTop: 6, color: "#9CB8D5", fontSize: 12 }, selfView: { position: "absolute", right: 14, top: 14, width: 107, height: 142, borderRadius: 16, backgroundColor: "#254B6D", borderWidth: 2, borderColor: "#76B8FF", justifyContent: "flex-end", padding: 9 }, selfLabel: { color: "#DCEBFA", fontSize: 10, fontWeight: "800" }, shareCanvas: { flex: 1, padding: 19, backgroundColor: "#123759" }, shareHeader: { padding: 13, borderRadius: 15, backgroundColor: "#1D527E" }, shareTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, shareSub: { marginTop: 5, color: "#B7D7F5", fontSize: 11, lineHeight: 16 }, shareCards: { flex: 1, paddingTop: 16, gap: 11 }, shareCard: { height: 72, borderRadius: 12, backgroundColor: "#2B6695" }, shareCardWide: { height: 128, backgroundColor: "#3A78A9" }, note: { marginTop: 13, color: "#9CB8D5", lineHeight: 17, textAlign: "center", fontSize: 11 }, controls: { marginTop: 15, gap: 9, flexDirection: "row", flexWrap: "wrap", justifyContent: "center" }, control: { paddingVertical: 11, paddingHorizontal: 12, borderRadius: 13, backgroundColor: "#153653", borderWidth: 1, borderColor: "#31587A" }, controlActive: { backgroundColor: "#D9EDFF", borderColor: "#D9EDFF" }, controlText: { color: "#DCEBFA", fontSize: 11, fontWeight: "900" }, controlTextActive: { color: "#0B3257" }, end: { paddingVertical: 11, paddingHorizontal: 14, borderRadius: 13, backgroundColor: "#DD4A54" }, endText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, pressed: { opacity: 0.65 } });
