import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";

import { Avatar } from "@/components/avatar";
import { IconButton } from "@/components/icon-button";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useMobileAuth } from "@/lib/auth-context";
import { mobileApi, type CallHistoryEntry } from "@/lib/mobile-api";

export default function CallsScreen() {
  const { token } = useMobileAuth();
  const [calls, setCalls] = useState<CallHistoryEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { if (!token) return; setLoading(true); try { setCalls(await mobileApi.callHistory(token)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không tải được lịch sử gọi."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  return <ScreenContainer containerClassName="bg-[#F4F7FB]" className="flex-1"><FlatList data={calls} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} tintColor="#1577E8" />} contentContainerStyle={styles.list} ListHeaderComponent={<View><View style={styles.header}><View><Text style={styles.title}>Nhật ký</Text><Text style={styles.subTitle}>Thời lượng được tính sau khi bên kia bắt máy</Text></View><View style={styles.shield}><IconSymbol name="lock.fill" size={16} color="#1577E8" /><Text style={styles.shieldText}>P2P</Text></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={styles.sectionTitle}>Gần đây</Text></View>} ListEmptyComponent={loading ? <View style={styles.empty}><ActivityIndicator color="#1577E8" /></View> : <Text style={styles.emptyText}>Chưa có cuộc gọi nào.</Text>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/call", params: { peerId: String(item.peer.id), mode: item.kind } })} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Avatar participant={{ id: String(item.peer.id), name: item.peer.displayName, initials: item.peer.displayName.split(" ").map((part) => part[0]).slice(0, 2).join(""), avatarColor: ["#8A63D2", "#D35D77", "#2F9E8F", "#3269C6"][item.peer.id % 4], avatarUrl: item.peer.avatarUrl ? mobileApi.mediaUrl(item.peer.avatarUrl) : null, presence: "offline" }} size={52} /><View style={styles.rowCopy}><View style={styles.nameLine}><Text style={[styles.name, item.direction === "missed" && styles.missed]}>{item.peer.displayName}</Text><IconSymbol name={item.kind === "video" ? "video.fill" : "phone.fill"} size={15} color={item.direction === "missed" ? "#E5484D" : "#7D8EA5"} /></View><Text style={[styles.meta, item.direction === "missed" && styles.missed]}>{callLabel(item)} · {formatDate(item.startedAt)}</Text><Text style={styles.duration}>{item.durationSeconds ? `${formatDuration(item.durationSeconds)} · ${item.status === "ended" ? "Đã kết thúc" : item.status}` : item.status === "missed" ? "Không bắt máy" : "Chưa kết nối"}</Text></View><IconButton name="phone.fill" onPress={() => router.push({ pathname: "/call", params: { peerId: String(item.peer.id), mode: item.kind } })} accessibilityLabel={`Gọi lại cho ${item.peer.displayName}`} background="#E8F2FF" color="#1577E8" size={19} /></Pressable>} /></ScreenContainer>;
}
function callLabel(item: CallHistoryEntry) { return item.direction === "missed" ? "Cuộc gọi nhỡ" : item.direction === "incoming" ? "Cuộc gọi đến" : "Cuộc gọi đi"; }
function formatDate(value: string | null | undefined) { const date = value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date) : "Không rõ thời gian"; }
function formatDuration(seconds: number) { const minutes = Math.floor(seconds / 60); return `${minutes}:${String(seconds % 60).padStart(2, "0")}`; }
const styles = StyleSheet.create({ list: { paddingHorizontal: 16, paddingBottom: 22 }, header: { paddingTop: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { fontSize: 29, lineHeight: 34, fontWeight: "900", letterSpacing: -0.9, color: "#0A284A" }, subTitle: { marginTop: 2, color: "#708096", fontSize: 12 }, shield: { borderRadius: 12, paddingHorizontal: 9, paddingVertical: 7, flexDirection: "row", gap: 4, alignItems: "center", backgroundColor: "#E8F2FF" }, shieldText: { color: "#1577E8", fontSize: 11, fontWeight: "800" }, error: { marginTop: 12, color: "#B93A40", fontSize: 12 }, sectionTitle: { marginTop: 20, marginBottom: 6, fontSize: 16, fontWeight: "900", color: "#112D4E" }, row: { minHeight: 78, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#E5ECF4" }, rowCopy: { flex: 1 }, nameLine: { flexDirection: "row", alignItems: "center", gap: 6 }, name: { fontSize: 16, fontWeight: "800", color: "#163252" }, meta: { marginTop: 4, fontSize: 12, color: "#7B8DA4" }, duration: { fontSize: 11, color: "#A0ACBC", marginTop: 2 }, missed: { color: "#E5484D" }, empty: { paddingTop: 56 }, emptyText: { paddingTop: 53, textAlign: "center", color: "#8492A4", fontSize: 13 }, pressed: { opacity: 0.58 } });
