import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";

import { Avatar } from "@/components/avatar";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol, type IconSymbolName } from "@/components/ui/icon-symbol";
import { useMobileAuth } from "@/lib/auth-context";

const rows: { icon: IconSymbolName; label: string; description: string }[] = [
  { icon: "bell.fill", label: "Thông báo", description: "Tin nhắn, cuộc gọi và lời mời kết bạn" },
  { icon: "lock.fill", label: "Quyền riêng tư", description: "Bạn bè mới có thể nhắn tin và gọi" },
  { icon: "wifi", label: "Kết nối & cuộc gọi", description: "P2P ưu tiên · TURN dự phòng" },
  { icon: "gearshape.fill", label: "Thiết lập", description: "Thiết bị và giao diện" },
];

export default function ProfileScreen() {
  const { user, signOut } = useMobileAuth();
  if (!user) return null;
  const participant = { id: String(user.id), name: user.displayName, initials: user.displayName.split(" ").map((word) => word[0]).slice(0, 2).join(""), avatarColor: "#1577E8", presence: "online" as const };
  return <ScreenContainer containerClassName="bg-[#F4F7FB]" className="flex-1"><ScrollView style={styles.page} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Text style={styles.title}>Cá nhân</Text><Pressable onPress={() => void signOut().then(() => router.replace("/auth"))} style={({ pressed }) => [styles.logout, pressed && styles.pressed]}><Text style={styles.logoutText}>Đăng xuất</Text></Pressable></View><View style={styles.profileCard}><Avatar participant={participant} size={72} showPresence={false} /><View style={styles.profileCopy}><Text style={styles.name}>{user.displayName}</Text><Text style={styles.handle}>@{user.username}</Text>{user.email ? <Text style={styles.email}>{user.email}</Text> : <Text style={styles.email}>Chưa thêm email</Text>}</View></View><View style={styles.notificationCard}><View style={styles.statusIcon}><IconSymbol name="bell.fill" size={19} color="#1577E8" /></View><View style={styles.statusCopy}><Text style={styles.statusTitle}>Push Notification</Text><Text style={styles.statusText}>Ứng dụng sẽ yêu cầu quyền và gửi token khi chạy development build trên thiết bị thật.</Text></View></View><Text style={styles.sectionTitle}>Tài khoản & thiết lập</Text><View style={styles.settingsCard}>{rows.map((row, index) => <View key={row.label} style={[styles.settingRow, index < rows.length - 1 && styles.divider]}><View style={styles.settingIcon}><IconSymbol name={row.icon} size={20} color="#1577E8" /></View><View style={styles.settingCopy}><Text style={styles.settingLabel}>{row.label}</Text><Text style={styles.settingDescription}>{row.description}</Text></View><IconSymbol name="chevron.right" size={21} color="#A1ADBD" /></View>)}</View><View style={styles.footer}><IconSymbol name="heart.fill" size={15} color="#E5484D" /><Text style={styles.footerText}>Kết Nối · Phiên bản realtime</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#F4F7FB" }, content: { paddingHorizontal: 16, paddingTop: 4, paddingBottom: 36 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { fontSize: 29, lineHeight: 34, fontWeight: "900", letterSpacing: -0.9, color: "#0A284A" }, logout: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 10, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E4EBF3" }, logoutText: { color: "#D3444B", fontSize: 12, fontWeight: "800" }, profileCard: { marginTop: 18, padding: 17, borderRadius: 22, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 15, borderWidth: 1, borderColor: "#EAF0F6", shadowColor: "#163252", shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 1 }, profileCopy: { flex: 1 }, name: { color: "#163252", fontSize: 20, fontWeight: "900" }, handle: { color: "#7B8DA4", marginTop: 2, fontSize: 13 }, email: { color: "#8090A4", marginTop: 5, fontSize: 11 }, notificationCard: { marginTop: 14, padding: 14, flexDirection: "row", gap: 12, borderRadius: 18, backgroundColor: "#EAF5FF", borderWidth: 1, borderColor: "#D9EBFC" }, statusIcon: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#FFFFFF" }, statusCopy: { flex: 1 }, statusTitle: { color: "#163252", fontWeight: "900", fontSize: 13 }, statusText: { color: "#627892", marginTop: 3, fontSize: 12, lineHeight: 17 }, sectionTitle: { marginTop: 25, marginBottom: 8, color: "#112D4E", fontWeight: "900", fontSize: 16 }, settingsCard: { borderRadius: 20, backgroundColor: "#FFFFFF", overflow: "hidden", borderWidth: 1, borderColor: "#EAF0F6" }, settingRow: { minHeight: 71, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, gap: 12 }, divider: { borderBottomWidth: 1, borderBottomColor: "#E8EEF5" }, settingIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#E8F2FF" }, settingCopy: { flex: 1 }, settingLabel: { color: "#163252", fontWeight: "800", fontSize: 14 }, settingDescription: { marginTop: 3, color: "#7C8BA0", fontSize: 11 }, footer: { marginTop: 23, alignSelf: "center", flexDirection: "row", alignItems: "center", gap: 6 }, footerText: { color: "#96A3B4", fontSize: 11 }, pressed: { opacity: 0.58 } });
